package model;

import java.util.Date;
import java.util.List;
import java.util.Map;

public interface AdminDao { 

	public boolean login(Map<String, Object> map);
	public int doc();
	public int dpc();
	public int duc();
	public int auc();
	public int luc();
	public int getCnt(String mapper);
	public boolean putValues(String mapper, Map map);
	public List<Map> getValues(String mapper);
	public Map getValues(String mapper, int val);
	public List<Map> getValues(String mapper, String table);
	public List<Map> getValues(String mapper, Map map);
	public boolean putImages(List list);
	public List getInfo_company();
	public boolean updateValues_info_company(List list);
	public boolean delInfo_company(String name);
	public int plusInfo_company(String name);
	public List getUuid_notice_img();
	public List getTerms(Map map);
	public List getDetail_terms(int num);
	public boolean updateValues_terms(Map map);
	public boolean plusTerms(Map map);
	public boolean delTerms(int num);
	public List getDetatil_notice(int num);
	public boolean delNotice_img(int num);
	public boolean updateImage_notice(Map map);
	public boolean delNotice(int num);
	public List getTarget_notice();
	public int getCount_notice(Map map);
	public int getCount_terms(Map map);
	public int getCount_counsel_user(Map map);
	public int getCount_counsel_seller(Map map);
	public List getList_counsel_user(Map map);
	public List getList_counsel_seller(Map map);
	public List getCounsel_category();
	public List getCounsel_user_detail(int num);
	public boolean updateCounsel_user_detail(Map map);
	public List getCounsel_seller_category();
	public List getCounsel_seller_detail(int num);
	public boolean updateCounsel_seller_detail(Map map);
	public List getPopup_list(Map map);
	public int getPopup_list_Count(Map map);
	public boolean updatePopup_onoff(Map map);
	public List getCupon_list();
	public boolean putPopup(Map map);
	public List getPopup_detail(Map map);
	public boolean updatePopup(Map map);
	public List getCupon_base_list(Map map);
	public int getCupon_base_count(Map map);
	public int checkCupon(Map map);
	public boolean updateCupon_base(Map map);
	public List getCupon_base_one(Map map);
	public boolean delCupon_base(Map map);
	public String checkPopup_img_uuid(Map map);
	public List getPopup_target(List li);
	public List getPopup_target_detail(Map map);
	public List getCupon_type_list();
	public boolean putCupon_base(Map map);
	public boolean delPopup(Map map);
	public boolean delCounsel_user(Map map);
	public boolean delCounsel_seller(Map map);
	public List<Map> admin_list(Map map);
	public int admin_list_count(Map map);
	public boolean admin_del(Map map);
	public boolean admin_modify(Map map);
	public boolean admin_create(Map map);
	public boolean createCupon(Map map);
	public Date getCupon_date(Map map);
	public int getUnableCupon();
	public int delUnableCupon();
	public int getDhl();
	public int getPoint();
	public boolean updateDhl(int charge);
	public boolean updatePoint(int rate);
}